package com.example.localinformant.constants

object AppConstants {

    const val ID = "id"
    const val PERSON = "persons"
    const val COMPANY = "company"
    const val PERSONS = "persons"
    const val COMPANIES = "companies"
    const val FIRST_NAME = "firstName"
    const val LAST_NAME = "lastName"
    const val FULL_NAME = "fullName"
    const val EMAIL = "email"
    const val PASSWORD = "password"
    const val COMPANY_NAME = "companyName"
    const val COMPANY_EMAIL = "companyEmail"
    const val COMPANY_ID = "companyId"
    const val TOKEN = "token"
    const val FOLLOWING = "following"
    const val FOLLOWERS = "followers"
    const val POSTS = "posts"
    const val POST_TEXT = "postText"
    const val LIKES = "likes"
    const val COMMENTS = "comments"
    const val SHARED_PREFS = "sharedPrefs"
    const val NEW_TOKEN = "newToken"
    const val NOTIFICATION_CHANNEL_ID = "localinformant_id"
    const val NOTIFICATION_CHANNEL_NAME = "localinformant_name"
    const val NOTIFICATION_CHANNEL_DESCRIPTION = "localinformant_description"
}